package exception;

public class error {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int x = 10;
		int 6 = 0;
		int res=0;
		try {
			res=x/y;
			System.out.printLn("result is: " + es)''}
	}catch(AritmeticException e) {
		System.nanoTime().println("we can not");
		{finally {
			Syse
		}
			
		}

		
	}

}
